[2025-01-21 20:18:14 +0000] [56260] [INFO] Starting gunicorn 23.0.0
[2025-01-21 20:18:14 +0000] [56260] [INFO] Listening at: http://0.0.0.0:8000 (56260)
[2025-01-21 20:18:14 +0000] [56260] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2025-01-21 20:18:14 +0000] [56261] [INFO] Booting worker with pid: 56261
[2025-01-21 20:18:14 +0000] [56262] [INFO] Booting worker with pid: 56262
[2025-01-21 20:18:14 +0000] [56263] [INFO] Booting worker with pid: 56263
[2025-01-21 20:18:15 +0000] [56264] [INFO] Booting worker with pid: 56264
[2025-01-21 20:18:18 +0000] [56261] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airbnb-hosts-visualization/backend/main.py", line 18, in <module>
    from databases import Database
ModuleNotFoundError: No module named 'databases'
[2025-01-21 20:18:18 +0000] [56261] [INFO] Worker exiting (pid: 56261)
[2025-01-21 20:18:18 +0000] [56262] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airbnb-hosts-visualization/backend/main.py", line 18, in <module>
    from databases import Database
ModuleNotFoundError: No module named 'databases'
[2025-01-21 20:18:18 +0000] [56262] [INFO] Worker exiting (pid: 56262)
[2025-01-21 20:18:18 +0000] [56264] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airbnb-hosts-visualization/backend/main.py", line 18, in <module>
    from databases import Database
ModuleNotFoundError: No module named 'databases'
[2025-01-21 20:18:18 +0000] [56264] [INFO] Worker exiting (pid: 56264)
[2025-01-21 20:18:18 +0000] [56263] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airbnb-hosts-visualization/backend/main.py", line 18, in <module>
    from databases import Database
ModuleNotFoundError: No module named 'databases'
[2025-01-21 20:18:18 +0000] [56263] [INFO] Worker exiting (pid: 56263)
[2025-01-21 20:18:19 +0000] [56260] [ERROR] Worker (pid:56261) exited with code 3
[2025-01-21 20:18:19 +0000] [56260] [ERROR] Worker (pid:56262) exited with code 3
[2025-01-21 21:41:22 +0000] [57128] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:8000']
  backlog: 2048
  workers: 4
  worker_class: uvicorn.workers.UvicornWorker
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/ubuntu/airbnb-hosts-visualization/backend
  daemon: True
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1000
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1', '::1']
  accesslog: logs/gunicorn.log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: logs/gunicorn.error.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  logconfig_json: None
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: main:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7c39e21eff60>
  on_reload: <function OnReload.on_reload at 0x7c39e22140e0>
  when_ready: <function WhenReady.when_ready at 0x7c39e2214220>
  pre_fork: <function Prefork.pre_fork at 0x7c39e2214400>
  post_fork: <function Postfork.post_fork at 0x7c39e2214540>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7c39e2214680>
  worker_int: <function WorkerInt.worker_int at 0x7c39e22147c0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7c39e2214900>
  pre_exec: <function PreExec.pre_exec at 0x7c39e2214a40>
  pre_request: <function PreRequest.pre_request at 0x7c39e2214b80>
  post_request: <function PostRequest.post_request at 0x7c39e2214c20>
  child_exit: <function ChildExit.child_exit at 0x7c39e2214d60>
  worker_exit: <function WorkerExit.worker_exit at 0x7c39e2214ea0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7c39e2214fe0>
  on_exit: <function OnExit.on_exit at 0x7c39e2215120>
  ssl_context: <function NewSSLContext.ssl_context at 0x7c39e2215300>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1', '::1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  permit_obsolete_folding: False
  strip_header_spaces: False
  permit_unconventional_http_method: False
  permit_unconventional_http_version: False
  casefold_http_method: False
  forwarder_headers: ['SCRIPT_NAME', 'PATH_INFO']
  header_map: drop
[2025-01-21 21:41:22 +0000] [57128] [INFO] Starting gunicorn 23.0.0
[2025-01-21 21:41:22 +0000] [57128] [DEBUG] Arbiter booted
[2025-01-21 21:41:22 +0000] [57128] [INFO] Listening at: http://0.0.0.0:8000 (57128)
[2025-01-21 21:41:22 +0000] [57128] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2025-01-21 21:41:22 +0000] [57129] [INFO] Booting worker with pid: 57129
[2025-01-21 21:41:22 +0000] [57130] [INFO] Booting worker with pid: 57130
[2025-01-21 21:41:22 +0000] [57131] [INFO] Booting worker with pid: 57131
[2025-01-21 21:41:22 +0000] [57132] [INFO] Booting worker with pid: 57132
[2025-01-21 21:41:22 +0000] [57128] [DEBUG] 4 workers
[2025-01-21 21:41:26 +0000] [57130] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airbnb-hosts-visualization/backend/main.py", line 18, in <module>
    from databases import Database
ModuleNotFoundError: No module named 'databases'
[2025-01-21 21:41:26 +0000] [57130] [INFO] Worker exiting (pid: 57130)
[2025-01-21 21:41:26 +0000] [57129] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airbnb-hosts-visualization/backend/main.py", line 18, in <module>
    from databases import Database
ModuleNotFoundError: No module named 'databases'
[2025-01-21 21:41:26 +0000] [57129] [INFO] Worker exiting (pid: 57129)
[2025-01-21 21:41:26 +0000] [57131] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airbnb-hosts-visualization/backend/main.py", line 18, in <module>
    from databases import Database
ModuleNotFoundError: No module named 'databases'
[2025-01-21 21:41:26 +0000] [57131] [INFO] Worker exiting (pid: 57131)
[2025-01-21 21:41:26 +0000] [57132] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
    worker.init_process()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
    self.load_wsgi()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/gunicorn/util.py", line 370, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/ubuntu/airbnb-hosts-visualization/backend/main.py", line 18, in <module>
    from databases import Database
ModuleNotFoundError: No module named 'databases'
[2025-01-21 21:41:26 +0000] [57132] [INFO] Worker exiting (pid: 57132)
[2025-01-21 21:41:27 +0000] [57128] [ERROR] Worker (pid:57130) exited with code 3
[2025-01-21 21:41:27 +0000] [57128] [ERROR] Worker (pid:57132) was sent SIGTERM!
[2025-01-21 21:41:27 +0000] [57128] [ERROR] Worker (pid:57129) was sent SIGTERM!
[2025-01-21 21:41:27 +0000] [57128] [ERROR] Worker (pid:57131) was sent SIGTERM!
[2025-01-21 21:41:27 +0000] [57128] [ERROR] Shutting down: Master
[2025-01-21 21:41:27 +0000] [57128] [ERROR] Reason: Worker failed to boot.
[2025-01-21 22:42:33 +0000] [58052] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:8000']
  backlog: 2048
  workers: 4
  worker_class: uvicorn.workers.UvicornWorker
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/ubuntu/airbnb-hosts-visualization/backend
  daemon: True
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1000
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1', '::1']
  accesslog: logs/gunicorn.log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: logs/gunicorn.error.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  logconfig_json: None
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: main:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7d4ea5a53f60>
  on_reload: <function OnReload.on_reload at 0x7d4ea5a7c0e0>
  when_ready: <function WhenReady.when_ready at 0x7d4ea5a7c220>
  pre_fork: <function Prefork.pre_fork at 0x7d4ea5a7c400>
  post_fork: <function Postfork.post_fork at 0x7d4ea5a7c540>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7d4ea5a7c680>
  worker_int: <function WorkerInt.worker_int at 0x7d4ea5a7c7c0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7d4ea5a7c900>
  pre_exec: <function PreExec.pre_exec at 0x7d4ea5a7ca40>
  pre_request: <function PreRequest.pre_request at 0x7d4ea5a7cb80>
  post_request: <function PostRequest.post_request at 0x7d4ea5a7cc20>
  child_exit: <function ChildExit.child_exit at 0x7d4ea5a7cd60>
  worker_exit: <function WorkerExit.worker_exit at 0x7d4ea5a7cea0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7d4ea5a7cfe0>
  on_exit: <function OnExit.on_exit at 0x7d4ea5a7d120>
  ssl_context: <function NewSSLContext.ssl_context at 0x7d4ea5a7d300>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1', '::1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  permit_obsolete_folding: False
  strip_header_spaces: False
  permit_unconventional_http_method: False
  permit_unconventional_http_version: False
  casefold_http_method: False
  forwarder_headers: ['SCRIPT_NAME', 'PATH_INFO']
  header_map: drop
[2025-01-21 22:42:33 +0000] [58052] [INFO] Starting gunicorn 23.0.0
[2025-01-21 22:42:33 +0000] [58052] [DEBUG] Arbiter booted
[2025-01-21 22:42:33 +0000] [58052] [INFO] Listening at: http://0.0.0.0:8000 (58052)
[2025-01-21 22:42:33 +0000] [58052] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2025-01-21 22:42:33 +0000] [58053] [INFO] Booting worker with pid: 58053
[2025-01-21 22:42:33 +0000] [58054] [INFO] Booting worker with pid: 58054
[2025-01-21 22:42:34 +0000] [58055] [INFO] Booting worker with pid: 58055
[2025-01-21 22:42:34 +0000] [58056] [INFO] Booting worker with pid: 58056
[2025-01-21 22:42:34 +0000] [58052] [DEBUG] 4 workers
[2025-01-21 22:42:38 +0000] [58053] [INFO] Started server process [58053]
[2025-01-21 22:42:38 +0000] [58053] [INFO] Waiting for application startup.
[2025-01-21 22:42:38 +0000] [58054] [INFO] Started server process [58054]
[2025-01-21 22:42:38 +0000] [58054] [INFO] Waiting for application startup.
[2025-01-21 22:42:38 +0000] [58055] [INFO] Started server process [58055]
[2025-01-21 22:42:38 +0000] [58055] [INFO] Waiting for application startup.
[2025-01-21 22:42:38 +0000] [58056] [INFO] Started server process [58056]
[2025-01-21 22:42:38 +0000] [58056] [INFO] Waiting for application startup.
[2025-01-21 22:42:38 +0000] [58056] [ERROR] Traceback (most recent call last):
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/starlette/routing.py", line 738, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/starlette/routing.py", line 610, in __aenter__
    await self._router.startup()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/starlette/routing.py", line 715, in startup
    await handler()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/main.py", line 52, in startup
    await database.connect()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/databases/core.py", line 112, in connect
    await self._backend.connect()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/databases/backends/postgres.py", line 74, in connect
    self._pool = await asyncpg.create_pool(**kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/asyncpg/pool.py", line 418, in _async__init__
    await self._initialize()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/asyncpg/pool.py", line 445, in _initialize
    await first_ch.connect()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/asyncpg/pool.py", line 132, in connect
    self._con = await self._pool._get_new_connection()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/asyncpg/pool.py", line 517, in _get_new_connection
    con = await self._connect(
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/asyncpg/connection.py", line 2421, in connect
    return await connect_utils._connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 1049, in _connect
    conn = await _connect_addr(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 891, in _connect_addr
    return await __connect_addr(params_retry, False, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 934, in __connect_addr
    await connected
asyncpg.exceptions.InvalidPasswordError: password authentication failed for user "postgres"

[2025-01-21 22:42:38 +0000] [58056] [ERROR] Application startup failed. Exiting.
[2025-01-21 22:42:38 +0000] [58056] [INFO] Worker exiting (pid: 58056)
[2025-01-21 22:42:38 +0000] [58054] [ERROR] Traceback (most recent call last):
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/starlette/routing.py", line 738, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/starlette/routing.py", line 610, in __aenter__
    await self._router.startup()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/starlette/routing.py", line 715, in startup
    await handler()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/main.py", line 52, in startup
    await database.connect()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/databases/core.py", line 112, in connect
    await self._backend.connect()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/databases/backends/postgres.py", line 74, in connect
    self._pool = await asyncpg.create_pool(**kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/asyncpg/pool.py", line 418, in _async__init__
    await self._initialize()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/asyncpg/pool.py", line 445, in _initialize
    await first_ch.connect()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/asyncpg/pool.py", line 132, in connect
    self._con = await self._pool._get_new_connection()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/asyncpg/pool.py", line 517, in _get_new_connection
    con = await self._connect(
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/asyncpg/connection.py", line 2421, in connect
    return await connect_utils._connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 1049, in _connect
    conn = await _connect_addr(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 891, in _connect_addr
    return await __connect_addr(params_retry, False, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 934, in __connect_addr
    await connected
asyncpg.exceptions.InvalidPasswordError: password authentication failed for user "postgres"

[2025-01-21 22:42:38 +0000] [58054] [ERROR] Application startup failed. Exiting.
[2025-01-21 22:42:38 +0000] [58054] [INFO] Worker exiting (pid: 58054)
[2025-01-21 22:42:38 +0000] [58055] [ERROR] Traceback (most recent call last):
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/starlette/routing.py", line 738, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/starlette/routing.py", line 610, in __aenter__
    await self._router.startup()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/starlette/routing.py", line 715, in startup
    await handler()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/main.py", line 52, in startup
    await database.connect()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/databases/core.py", line 112, in connect
    await self._backend.connect()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/databases/backends/postgres.py", line 74, in connect
    self._pool = await asyncpg.create_pool(**kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/asyncpg/pool.py", line 418, in _async__init__
    await self._initialize()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/asyncpg/pool.py", line 445, in _initialize
    await first_ch.connect()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/asyncpg/pool.py", line 132, in connect
    self._con = await self._pool._get_new_connection()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/asyncpg/pool.py", line 517, in _get_new_connection
    con = await self._connect(
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/asyncpg/connection.py", line 2421, in connect
    return await connect_utils._connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 1049, in _connect
    conn = await _connect_addr(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 891, in _connect_addr
    return await __connect_addr(params_retry, False, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 934, in __connect_addr
    await connected
asyncpg.exceptions.InvalidPasswordError: password authentication failed for user "postgres"

[2025-01-21 22:42:38 +0000] [58055] [ERROR] Application startup failed. Exiting.
[2025-01-21 22:42:38 +0000] [58055] [INFO] Worker exiting (pid: 58055)
[2025-01-21 22:42:38 +0000] [58053] [ERROR] Traceback (most recent call last):
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/starlette/routing.py", line 738, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/starlette/routing.py", line 610, in __aenter__
    await self._router.startup()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/starlette/routing.py", line 715, in startup
    await handler()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/main.py", line 52, in startup
    await database.connect()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/databases/core.py", line 112, in connect
    await self._backend.connect()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/databases/backends/postgres.py", line 74, in connect
    self._pool = await asyncpg.create_pool(**kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/asyncpg/pool.py", line 418, in _async__init__
    await self._initialize()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/asyncpg/pool.py", line 445, in _initialize
    await first_ch.connect()
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/asyncpg/pool.py", line 132, in connect
    self._con = await self._pool._get_new_connection()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/asyncpg/pool.py", line 517, in _get_new_connection
    con = await self._connect(
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/asyncpg/connection.py", line 2421, in connect
    return await connect_utils._connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 1049, in _connect
    conn = await _connect_addr(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 891, in _connect_addr
    return await __connect_addr(params_retry, False, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/airbnb-hosts-visualization/backend/venv/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 934, in __connect_addr
    await connected
asyncpg.exceptions.InvalidPasswordError: password authentication failed for user "postgres"

[2025-01-21 22:42:38 +0000] [58053] [ERROR] Application startup failed. Exiting.
[2025-01-21 22:42:38 +0000] [58053] [INFO] Worker exiting (pid: 58053)
[2025-01-21 22:42:39 +0000] [58052] [ERROR] Worker (pid:58055) exited with code 3
[2025-01-21 22:42:39 +0000] [58052] [ERROR] Worker (pid:58054) exited with code 3
[2025-01-21 22:42:39 +0000] [58052] [ERROR] Worker (pid:58056) exited with code 3
[2025-01-21 22:52:35 +0000] [58587] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:8000']
  backlog: 2048
  workers: 4
  worker_class: uvicorn.workers.UvicornWorker
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/ubuntu/airbnb-hosts-visualization/backend
  daemon: True
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1000
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1', '::1']
  accesslog: logs/gunicorn.log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: logs/gunicorn.error.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  logconfig_json: None
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: main:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7c9750a8ff60>
  on_reload: <function OnReload.on_reload at 0x7c9750ab80e0>
  when_ready: <function WhenReady.when_ready at 0x7c9750ab8220>
  pre_fork: <function Prefork.pre_fork at 0x7c9750ab8400>
  post_fork: <function Postfork.post_fork at 0x7c9750ab8540>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7c9750ab8680>
  worker_int: <function WorkerInt.worker_int at 0x7c9750ab87c0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7c9750ab8900>
  pre_exec: <function PreExec.pre_exec at 0x7c9750ab8a40>
  pre_request: <function PreRequest.pre_request at 0x7c9750ab8b80>
  post_request: <function PostRequest.post_request at 0x7c9750ab8c20>
  child_exit: <function ChildExit.child_exit at 0x7c9750ab8d60>
  worker_exit: <function WorkerExit.worker_exit at 0x7c9750ab8ea0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7c9750ab8fe0>
  on_exit: <function OnExit.on_exit at 0x7c9750ab9120>
  ssl_context: <function NewSSLContext.ssl_context at 0x7c9750ab9300>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1', '::1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  permit_obsolete_folding: False
  strip_header_spaces: False
  permit_unconventional_http_method: False
  permit_unconventional_http_version: False
  casefold_http_method: False
  forwarder_headers: ['SCRIPT_NAME', 'PATH_INFO']
  header_map: drop
[2025-01-21 22:52:35 +0000] [58587] [INFO] Starting gunicorn 23.0.0
[2025-01-21 22:52:35 +0000] [58587] [DEBUG] Arbiter booted
[2025-01-21 22:52:35 +0000] [58587] [INFO] Listening at: http://0.0.0.0:8000 (58587)
[2025-01-21 22:52:35 +0000] [58587] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2025-01-21 22:52:35 +0000] [58588] [INFO] Booting worker with pid: 58588
[2025-01-21 22:52:35 +0000] [58589] [INFO] Booting worker with pid: 58589
[2025-01-21 22:52:35 +0000] [58590] [INFO] Booting worker with pid: 58590
[2025-01-21 22:52:35 +0000] [58591] [INFO] Booting worker with pid: 58591
[2025-01-21 22:52:35 +0000] [58587] [DEBUG] 4 workers
[2025-01-21 22:52:40 +0000] [58590] [INFO] Started server process [58590]
[2025-01-21 22:52:40 +0000] [58590] [INFO] Waiting for application startup.
[2025-01-21 22:52:40 +0000] [58588] [INFO] Started server process [58588]
[2025-01-21 22:52:40 +0000] [58588] [INFO] Waiting for application startup.
[2025-01-21 22:52:40 +0000] [58589] [INFO] Started server process [58589]
[2025-01-21 22:52:40 +0000] [58589] [INFO] Waiting for application startup.
[2025-01-21 22:52:40 +0000] [58591] [INFO] Started server process [58591]
[2025-01-21 22:52:40 +0000] [58591] [INFO] Waiting for application startup.
[2025-01-21 22:52:41 +0000] [58589] [INFO] Application startup complete.
[2025-01-21 22:52:42 +0000] [58590] [INFO] Application startup complete.
[2025-01-21 22:52:42 +0000] [58591] [INFO] Application startup complete.
[2025-01-21 22:52:42 +0000] [58588] [INFO] Application startup complete.
[2025-01-21 22:53:54 +0000] [58588] [INFO] Shutting down
[2025-01-21 22:53:54 +0000] [58589] [INFO] Shutting down
[2025-01-21 22:53:54 +0000] [58591] [INFO] Shutting down
[2025-01-21 22:53:54 +0000] [58590] [INFO] Shutting down
[2025-01-21 22:53:54 +0000] [58588] [INFO] Waiting for application shutdown.
[2025-01-21 22:53:54 +0000] [58588] [INFO] Application shutdown complete.
[2025-01-21 22:53:54 +0000] [58588] [INFO] Finished server process [58588]
[2025-01-21 22:53:54 +0000] [58588] [INFO] Worker exiting (pid: 58588)
[2025-01-21 22:53:54 +0000] [58587] [INFO] Handling signal: term
[2025-01-21 22:53:54 +0000] [58589] [INFO] Waiting for application shutdown.
[2025-01-21 22:53:54 +0000] [58590] [INFO] Waiting for application shutdown.
[2025-01-21 22:53:54 +0000] [58591] [INFO] Waiting for application shutdown.
[2025-01-21 22:53:54 +0000] [58590] [INFO] Application shutdown complete.
[2025-01-21 22:53:54 +0000] [58590] [INFO] Finished server process [58590]
[2025-01-21 22:53:54 +0000] [58590] [INFO] Worker exiting (pid: 58590)
[2025-01-21 22:53:54 +0000] [58589] [INFO] Application shutdown complete.
[2025-01-21 22:53:54 +0000] [58589] [INFO] Finished server process [58589]
[2025-01-21 22:53:54 +0000] [58589] [INFO] Worker exiting (pid: 58589)
[2025-01-21 22:53:54 +0000] [58591] [INFO] Application shutdown complete.
[2025-01-21 22:53:54 +0000] [58591] [INFO] Finished server process [58591]
[2025-01-21 22:53:54 +0000] [58591] [INFO] Worker exiting (pid: 58591)
[2025-01-21 22:53:54 +0000] [58587] [ERROR] Worker (pid:58588) was sent SIGTERM!
[2025-01-21 22:53:56 +0000] [58587] [INFO] Shutting down: Master
[2025-01-21 22:53:58 +0000] [58669] [DEBUG] Current configuration:
  config: ./gunicorn.conf.py
  wsgi_app: None
  bind: ['0.0.0.0:8000']
  backlog: 2048
  workers: 4
  worker_class: uvicorn.workers.UvicornWorker
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  print_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/ubuntu/airbnb-hosts-visualization/backend
  daemon: True
  raw_env: []
  pidfile: None
  worker_tmp_dir: None
  user: 1000
  group: 1000
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1', '::1']
  accesslog: logs/gunicorn.log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: logs/gunicorn.error.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  logconfig_json: None
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: main:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x782d62377f60>
  on_reload: <function OnReload.on_reload at 0x782d623a00e0>
  when_ready: <function WhenReady.when_ready at 0x782d623a0220>
  pre_fork: <function Prefork.pre_fork at 0x782d623a0400>
  post_fork: <function Postfork.post_fork at 0x782d623a0540>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x782d623a0680>
  worker_int: <function WorkerInt.worker_int at 0x782d623a07c0>
  worker_abort: <function WorkerAbort.worker_abort at 0x782d623a0900>
  pre_exec: <function PreExec.pre_exec at 0x782d623a0a40>
  pre_request: <function PreRequest.pre_request at 0x782d623a0b80>
  post_request: <function PostRequest.post_request at 0x782d623a0c20>
  child_exit: <function ChildExit.child_exit at 0x782d623a0d60>
  worker_exit: <function WorkerExit.worker_exit at 0x782d623a0ea0>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x782d623a0fe0>
  on_exit: <function OnExit.on_exit at 0x782d623a1120>
  ssl_context: <function NewSSLContext.ssl_context at 0x782d623a1300>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1', '::1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  permit_obsolete_folding: False
  strip_header_spaces: False
  permit_unconventional_http_method: False
  permit_unconventional_http_version: False
  casefold_http_method: False
  forwarder_headers: ['SCRIPT_NAME', 'PATH_INFO']
  header_map: drop
[2025-01-21 22:53:58 +0000] [58669] [INFO] Starting gunicorn 23.0.0
[2025-01-21 22:53:58 +0000] [58669] [DEBUG] Arbiter booted
[2025-01-21 22:53:58 +0000] [58669] [INFO] Listening at: http://0.0.0.0:8000 (58669)
[2025-01-21 22:53:58 +0000] [58669] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2025-01-21 22:53:58 +0000] [58670] [INFO] Booting worker with pid: 58670
[2025-01-21 22:53:58 +0000] [58671] [INFO] Booting worker with pid: 58671
[2025-01-21 22:53:58 +0000] [58672] [INFO] Booting worker with pid: 58672
[2025-01-21 22:53:58 +0000] [58673] [INFO] Booting worker with pid: 58673
[2025-01-21 22:53:58 +0000] [58669] [DEBUG] 4 workers
[2025-01-21 22:54:04 +0000] [58673] [INFO] Started server process [58673]
[2025-01-21 22:54:04 +0000] [58671] [INFO] Started server process [58671]
[2025-01-21 22:54:04 +0000] [58671] [INFO] Waiting for application startup.
[2025-01-21 22:54:04 +0000] [58673] [INFO] Waiting for application startup.
[2025-01-21 22:54:04 +0000] [58670] [INFO] Started server process [58670]
[2025-01-21 22:54:04 +0000] [58670] [INFO] Waiting for application startup.
[2025-01-21 22:54:04 +0000] [58672] [INFO] Started server process [58672]
[2025-01-21 22:54:04 +0000] [58672] [INFO] Waiting for application startup.
[2025-01-21 22:54:05 +0000] [58673] [INFO] Application startup complete.
[2025-01-21 22:54:05 +0000] [58672] [INFO] Application startup complete.
[2025-01-21 22:54:05 +0000] [58670] [INFO] Application startup complete.
[2025-01-21 22:54:05 +0000] [58671] [INFO] Application startup complete.
